# Exemple de requêtes http

### Get token
POST http://localhost/authentication_token
Content-Type: application/json

{
  "email": "admin@lesmeilleurs.com",
  "password": "administration"
}

### Get users
GET http://localhost/api/users
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2OTk5OTUxOTAsImV4cCI6MTY5OTk5ODc5MCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQGxlc21laWxsZXVycy5jb20ifQ.meFRTcmQurck5yI_UqgGaTSflrOQRRX_LweMMdgtSOWPTkjckZP0gfHbwUQ1SCiEIeNa5kzkgRUddwZgidx1lIQXEU4WBnSTMNz675ecHLifkT2QbdrvIxYCWfadKKFZFFhy84eK49k-rQYLHcH_LhzcXK9x3Rruez4Eu7GpOtE_eBfCoV9M9HpgePsabv_FHBab68lbzOo4DPlx1sEc11IyzK69JdMW_lj_iZjeuWSuVXyo8P8lBslhdHrKLHNcvNfqVOzI-6w1jBIJkhzqcUkU778Owmbk8Y0YejxVat5KNcpAEocXwvFFqlQ__fj1zOoeJVIoC_DRayz7Ll-FQQ
Accept: application/json

### Create client user
POST http://localhost/api/users
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDAxMjU4NTAsImV4cCI6MTcwMDEyOTQ1MCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQGxlc21laWxsZXVycy5jb20ifQ.tBInI4O-bc-Tm_vg08ZygDMWP-BN7rGIe3EXkz6kxcTHFNhKgeSU8CpWpPwR72NMf6dWE5QkMNyr87nyVPgl6PTi-84Vcy4EOMfyQpRdj3GgzdfT1N9TQkF66EV6gSb3rVxGGqv-H_YIHkIuj_8QmzQrArQ45jIdoc-8m6JTcTfPSDHSw4OWtGorNYgKp4vR_Vx2A_kNvEasv3qWP6g_88_7OrfMwoTSzkTwJpD6ng4AMbULRcIQvQWGcAkkpsU-tSUukYvrrObnqy52siOSDv8GiQkKVHmlSxP2sPG1Jy3n5tQ7g9AIqURLkIj06Pu_qVCrUH1f5eP47vMiYi0NsQ
Content-Type: application/json

{
  "email": "test@ftp.com",
  "password": "abcdefg",
  "fullName": "test bug"
}

### Delete the user 4
DELETE http://localhost/api/users/4
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDAxMjU4NTAsImV4cCI6MTcwMDEyOTQ1MCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQGxlc21laWxsZXVycy5jb20ifQ.tBInI4O-bc-Tm_vg08ZygDMWP-BN7rGIe3EXkz6kxcTHFNhKgeSU8CpWpPwR72NMf6dWE5QkMNyr87nyVPgl6PTi-84Vcy4EOMfyQpRdj3GgzdfT1N9TQkF66EV6gSb3rVxGGqv-H_YIHkIuj_8QmzQrArQ45jIdoc-8m6JTcTfPSDHSw4OWtGorNYgKp4vR_Vx2A_kNvEasv3qWP6g_88_7OrfMwoTSzkTwJpD6ng4AMbULRcIQvQWGcAkkpsU-tSUukYvrrObnqy52siOSDv8GiQkKVHmlSxP2sPG1Jy3n5tQ7g9AIqURLkIj06Pu_qVCrUH1f5eP47vMiYi0NsQ